organization: hashi-demos-apj
workspace_name: dev1-cli-workspace
create_project: false
project_name: Simons Project
create_repo: false
create_variable_set: true
workspace_tags:
  - nsx
var_sets:
  my-set2:
    tags:
      - nsx
    variable_set_name: my-set2
    variables:
      AWS_REGION:
        category: env
        description: (Required) AWS Region where the resources will be instantiated.
        hcl: false
        sensitive: false
        value: ap-southeast-1
      aws_tag_owner:
        category: terraform
        description: (Required) Owner of all resources that will be created - Use an
            email address
        hcl: false
        sensitive: true
        value: my-email@email.com
      aws_tag_ttl:
        category: terraform
        description: (Required) TTL of the resources that will be provisioned for this
            demo. Specified in hours
        hcl: false
        sensitive: false
        value: "8760"
